### ISSUE TITLE
`workspaces` name is too generic

### ISSUE THREAD

**Issue by frol** [near/near-workspaces-rs#74]
Please, consider renaming the repo and crate name to `near-workspaces-rs` (I am still confused why it is named as "workspaces" to begin with 🤷‍♂️ )

This feedback was brought by a few people including Illia, and I agree with them that reading `workspaces = "..."` in Cargo.toml file of a contract that uses it does not give you any relevant hints.

**Comment by ChaoticTempest** [comment]
I think @OnlyOneJMJQ had the original context as to why it was called only `workspaces` since he shopped that name around, but we're currently publishing this crate as both `workspaces` and `near-workspaces` anyways. If `near-workspaces` is final then, I'll make a PR to rename everything in this repo to that then

**Comment by willemneal** [comment]
We had shopped it around and the idea was that the workspace should be more than just testing, but rather a tool for setting up environments to run in.  As #66 points out it could broaden in its aims.

**Comment by frol** [comment]
Thinking more about it, I feel the functionality that is built here reminds me near-api-rs (high-level programmatic interactions with the blockchain), especially if we refactor/rename the concept of workers and keep sandbox as a separate crate that is easily pluggable into this near-api-rs. What do you think about this direction of thought?

**Comment by shariffdev** [comment]
We can close this issue @frol
